// <auto-generated />
using Amoisuntke.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amoisuntke.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127170458_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amoisuntke.Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Coverage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Splash")
                        .HasColumnType("int");

                    b.Property<int>("Tank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            Coverage = 360,
                            Description = "ყოველდღიურ სტრესთან საბრძოლველად საჭიროა გვქონდეს ადგილი სადაც განიტვირთებით, ეს მოწყობილობა დაგეხმარებათ თქვენი გარემო მეტად მყუდრო და სასიამოვნო გახადოთ",
                            DiscountPrice = 125.0,
                            IsExpired = false,
                            IsSecured = true,
                            Name = "ვულკანის ჰაერის დამატენიანებელი",
                            Price = 185.0,
                            Quantity = 5,
                            Splash = 36,
                            Tank = 30
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            Coverage = 360,
                            Description = "ყოველდღიურ სტრესთან საბრძოლველად საჭიროა გვქონდეს ადგილი სადაც განიტვირთებით, ეს მოწყობილობა დაგეხმარებათ თქვენი გარემო მეტად მყუდრო და სასიამოვნო გახადოთ",
                            DiscountPrice = 125.0,
                            IsExpired = false,
                            IsSecured = true,
                            Name = "ჰაერის დამატენიანებელი",
                            Price = 185.0,
                            Quantity = 5,
                            Splash = 36,
                            Tank = 30
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            Coverage = 0,
                            Description = "არომატი რომლის აღწერაც არც თუ ისე მარტივია, ზედა ნოტებია თამბაქოს ფოთოლი და პიკანტური ნოტები, შუა ნოტებია თამბაქოს ყვავილი, ვანილი და კაკაო, საბაზო ნოტები ხმელი ხილი და ხის ნოტები",
                            DiscountPrice = 0.0,
                            IsExpired = false,
                            IsSecured = false,
                            Name = "სურნელოვანი ეთერზეთი - Tobacco Vanille 10ml",
                            Price = 25.0,
                            Quantity = 15,
                            Splash = 10,
                            Tank = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
